# Generated by Django 5.2 on 2025-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0004_pendingmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='contribution_proofs/'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], max_length=20),
        ),
    ]
