# Generated by Django 5.2 on 2025-04-29 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0005_contribution_proof_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='disbursement_receipts/'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='category',
            field=models.CharField(blank=True, choices=[('school_fees', 'School Fees'), ('marriage', 'Marriage'), ('funeral', 'Funeral'), ('job_loss', 'Job Loss'), ('medical', 'Medical'), ('baby_dedication', 'Baby Dedication'), ('food', 'Food'), ('rent', 'House Rent'), ('others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='welfare.member'),
        ),
        migrations.AlterField(
            model_name='welfarerequest',
            name='category',
            field=models.CharField(choices=[('school_fees', 'School Fees'), ('marriage', 'Marriage'), ('funeral', 'Funeral'), ('job_loss', 'Job Loss'), ('medical', 'Medical'), ('baby_dedication', 'Baby Dedication'), ('food', 'Food'), ('rent', 'House Rent'), ('others', 'Others')], max_length=50),
        ),
    ]
