# Generated by Django 5.2 on 2025-04-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0006_disbursement_attachment_disbursement_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welfarerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('declined', 'Declined'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
