# Generated by Django 5.2 on 2025-05-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0007_alter_welfarerequest_status'),
    ]

    operations = [
    ]
