# Generated by Django 5.2 on 2025-05-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0008_fill_missing_member_emails'),
    ]

    operations = [
    ]
