# Generated by Django 5.2 on 2025-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0009_fill_missing_admin_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
