# Generated by Django 5.2 on 2025-05-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
