# Generated by Django 5.2 on 2025-05-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '000X_seed_system_settings'),
        ('welfare', '0013_systemsetting'),
    ]

    operations = [
    ]
