# Generated by Django 5.2 on 2025-06-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0014_merge_000X_seed_system_settings_0013_systemsetting'),
        ('welfare', '0015_add_contact_support_setting'),
    ]

    operations = [
    ]
